<?php

return [     
    'model_catgory' => [
        [
          'category_name' => 'Toyota',
          'children' => [
            'ALLION', 'ALPHARD', 'ALTEZZA', 'AQUA', 'ARISTO', 'AURIS', 'AVENSIS VERSO', 'AVENSIS WAGON', 'AVENSIS', 'BB', 'BELTA', 'BLADE', 'BREVIS', 'CALDINA VAN', 'CALDINA', 'CAMI', 'CARINA', 'CAMRY', 'CELICA', 'CELSIOR', 'CHASER', 'COASTER', 'COROLLA AXIO', 'COROLLA FIELDER', 'COROLLA RUMION', 'COROLLA RUNX', 'COROLLA SEDAN', 'COROLLA SPACIO', 'COROLLA TOURING WAGON', 'COROLLA VAN', 'COROLLA', 'CORSA', 'CORONA PREMIO', 'CROWN MAJESTA','COROLLA VERSO','CROWN', 'DUET', 'DYNA ROUTE VAN', 'DYNA TRUCK', 'DYNA URBAN SUPPORTER', 'ESTIMA', 'FJ CRUISER', 'FORTUNER', 'FUN CARGO', 'GAIA', 'GRANVIA','GRAND HIACE', 'HARRIER', 'HIACE COMMUTER', 'HIACE TRUCK', 'HIACE VAN', 'HIACE WAGON', 'HILUX SURF', 'HILUX TRUCK', 'HILUX', 'IPSUM', 'IQ', 'ISIS','IST', 'KLUGER', 'LAND CRUISER PRADO','LAND CRUISER', 'LITEACE NOAH', 'LITEACE TRUCK', 'LITEACE VAN', 'MARK II', 'MARK X ZIO', 'MARK X', 'MR-S', 'NADIA', 'NOAH', 'PASSO SETTE', 'PASSO', 'PLATZ', 'PORTE', 'PREMIO', 'PREVIA', 'PRIUS ALPHA', 'PRIUS', 'PROBOX VAN', 'PROBOX WAGON', 'PROGRES', 'RACTIS', 'RAUM','RAV4','RDX', 'REGIUS WAGON', 'REGIUSACE COMMUTER','REGIUSACE VAN', 'RUSH', 'SAI','SOARER', 'SPADE', 'SPRINTER CARIB','SIENTA','SPRINTER SEDAN', 'STARLET', 'SUCCEED VAN', 'SUCCEED WAGON', 'TOURING HIACE', 'TOWNACE NOAH', 'TOWNACE TRUCK', 'TOWNACE VAN', 'TOYOACE','TUNDRA', 'VANGUARD', 'VELLFIRE', 'VEROSSA', 'VISTA ARDEO', 'VITZ', 'VOXY','VOLTZ', 'WILL VS', 'YARIS'
          ]
        ],
        [
          'category_name' => 'MITSUBISHI',
          'children' => [
            'AERO MIDI', 'AIRTREK', 'CANTER GUTS', 'CANTER', 'CARISMA', 'CHALLENGER', 'COLT', 'COLTPLUS', 'DELICA CARGO', 'DELICA D5', 'DELICA SPACEGEAR', 'DELICA TRUCK', 'DELICA VAN', 'DION', 'EK WAGON', 'FIGHTER DUMP', 'FIGHTER MIGNON DUMP', 'FIGHTER MIGNON', 'FIGHTER', 'GALANT FORTIS', 'GRANDIS', 'GREAT', 'JEEP', 'L200', 'L300', 'L400', 'LANCER CARGO', 'LANCER EVOLUTION', 'LANCER EVOLUTION VII', 'LANCER EVOLUTION VIII', 'LANCER', 'MINICA', 'MINICAB TRUCK', 'MINICAB VAN', 'OUTLANDER', 'PAJERO IO', 'PAJERO JR', 'PAJERO MINI', 'PAJERO', 'RVR','ROSA', 'SPACE GEER', 'STRADA', 'SUPER GREAT'
          ]
        ],
        [
          'category_name' => 'Nissan',
          'children' => [
            'AD', 'ALMERA', 'ATLAS','ALTIMA', 'BIG THUMB', 'BLUEBIRD SYLPHY', 'CARAVAN COACH', 'CARAVAN VAN', 'CARAVAN', 'CEDRIC', 'CIMA', 'CIVILIAN', 'CLIPPER TRUCK', 'CLIPPER VAN', 'CONDOR', 'CUBE CUBIC', 'CUBE', 'DATSUN','DEXPERT','DUALIS', 'ELGRAND', 'FAIRLADY Z', 'FUGA', 'HOMY COACH', 'HOMY VAN', 'JUKE','KUON', 'LAFESTA', 'LATIO', 'LIBERTY', 'MARCH', 'MURANO','MOCO', 'NAVARA', 'NOTE', 'OTTI', 'PAO', 'PATROL GR', 'PRESAGE', 'PRIMERA WAGON', 'PRIMERA', 'SAFARI', 'SERENA', 'SKYLINE GT-R', 'SKYLINE', 'STAGEA', 'SUNNY TRUCK', 'SUNNY','SKYLINE COUPE', 'TEANA', 'TERRANO REGULUS', 'TERRANO', 'TIIDA LATIO', 'TIIDA', 'URVAN','UD', 'VANETTE TRUCK', 'VANETTE VAN', 'WINGROAD', 'X-TRAIL'
          ],
        ],
        [
          'category_name' => 'ISUZU',
          'children' => [
             'ASKA', 'BIGHORN', 'COMO', 'D-MAX', 'ELF', 'FORWARD', 'FARGO', 'GIGA', 'JOURNEY', 'JUSTON', 'MU', 'WIZARD'
          ],
        ],
        [
          'category_name' => 'Hino',
          'children' => [
            'DOLPHIN', 'DUTRO', 'LIESSE II', 'MELPHA', 'PROFIA', 'RANGER2', 'RAINBOW', 'RANGER'
          ],
        ],
        [
          'category_name' => 'Suzuki',
          'children' => [
            'ALTO', 'CARRY', 'ESCUDO', 'EVERY', 'GRAND ESCUDO', 'JIMNY SIERRA', 'JIMNY', 'JIMNY WIDE', 'KEI', 'LANDY', 'SX4', 'SWIFT', 'SPLASH', 'WAGON R'
          ],
        ],
        [
          'category_name' => 'Benz',
          'children' => [
           'Actros', 'C-Class', 'E-Class'
          ],
        ],
        [
          'category_name' => 'Volvo',
          'children' => [
            '1800', '240', '240 WAGON', '244', '245 WAGON', '740', '740 ESTATE', '760', '850', '850 ESTATE', '940', '940 ESTATE', '960', '960 ESTATE', 'AMAZON', 'C30', 'C70', 'CROSS COUNTRY', 'S40', 'S60', 'S70', 'S80', 'S90', 'V40', 'V50', 'V60', 'V70', 'V90', 'XC40', 'XC60', 'XC70', 'XC90'
          ],
        ],
        [
          'category_name' => 'BMW',
          'children' => [
            '120I', '1 SERIES', '2 SERIES', '3 SERIES', '3 SERIES CABRIORET', '4 SERIES', '5 SERIES', '6 SERIES', '7 SERIES', '8 SERIES', 'ACTIVE HYBRID 3', 'ALPINA', 'i3', 'i8', 'JETTA', 'M MODEL', 'M8', 'MINI', 'MINI ONE', 'OTHER', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z3', 'Z4'
          ],
        ],
        [
          'category_name' => 'Ford',
          'children' => [
            'BRONCO', 'E350', 'ECOSPORT', 'ESCAPE', 'EXCURSION', 'EXPEDITION', 'EXPLORER', 'F150', 'FESTIVA', 'FIESTA', 'FLEX', 'FOCUS', 'FREDA', 'J80', 'Ka', 'KUGA', 'MONDEO', 'MUSTANG', 'OTHER', 'RANGER', 'WINNEBAGO'
          ],
        ],
        [
          'category_name' => 'Honda',
          'children' => [
             'ACCORD','ACTY TRUCK','ACTY VAN','AIRWAVE','AVANCIER','CAPA','CIVIC HYBRID', 'Civic','Corvette','CR-V','CR-Z','CROSSROAD', 'EDIX','ELEMENT','ELYSION','FIT HYBRID','FIT SHUTTLE', 'FIT','FREED','HR-V','INSIGHT','INSIGHT EXCLUSIVE', 'INSPIRE', 'INTEGRA', 'LEGEND', 'LIFE', 'MDX', 'MOBILIO', 'MOBILIO SPIKE', 'ODYSSEY','STEP WGN','STREAM',
          ],
        ],
        [
          'category_name' => 'Mazda',
          'children' => [
            'ATENZA WAGON','ATENZA SPORT WAGON','ATENZA SPORT','ATENZA','AXELA SPORT', 'AXELA','BIANTE','BONGO BRAWNY VAN','BONGO FRIENDEE','BONGO TRUCK','BONGO VAN','B-SERIES','CAROL','CX-5','CX-7','DEMIO', 'E2200', 'FAMILIA S-WAGON', 'FAMILIA VAN','LEVANTE', 'MAZDA5','MPV', 'PREMACY','ROADSTER','RX-8', 'TRIBUTE','TITAN DASH', 'TITAN','VERISA',
          ],
        ],
        [
          'category_name' => 'Daihatsu',
          'children' => [
            'BE-GO','BOON','COO','DELTA','ESSE', 'HIJET','HIJET CARGO', 'MOVE', 'MIRAGINO', 'MIRA ES', 'MIRA','NAKED','TERIOS', 'TERIOS KID'
          ],
        ],
        [
          'category_name' => 'Subaru',
          'children' => [
            'EXIGA', 'FORESTER', 'IMPREZA ANESIS', 'IMPREZA G4', 'IMPREZA SPORTS', 'IMPREZA SPORTSWAGON', 'IMPREZA WRX', 'IMPREZA WRX STI', 'IMPREZA', 'LEGACY B4', 'LEGACY TOURING WAGON', 'OUTBACK', 'PLEO', 'SAMBAR TRUCK','SAMBAR','VIVIO'
          ],
        ],
    ],
    'body_type' =>[
        'Bus', 'Truck', 'Van', 'SUV', 'Sedan', 'Hatchback', 'Pick Up', 'Machinery', 'Tractor'
    ],
    'fuel_type' =>[
        'Diesel', 'Electric', 'Gasoline', 'Hybrid', 'Petrol'
    ],
    'fuel_type' =>[
        'Diesel', 'Electric', 'Gasoline', 'Hybrid', 'Petrol'
    ],
    'drive_type' => [
        '2 Wheel', '4 Wheel'
    ],
    'transmission' =>[
        'Automatic', 'Manual', 'Semi-Automatic'
    ],  
    'steering' =>[
        'Right', 'Left'
    ],
    'doors' =>[
        1, 2, 3, 4, 5
    ],
    'country' =>[
        "Zambia",
        "Tanzania",
        "Uganda",
        "D.R Congo",
        "Zimbabwe",
        "Mozambique",
        "Malawi",
        "Sudan",
        "Kenya",
        "Botswana",
        "Burundi",
        "Afghanistan",
        "Albania",
        "Algeria",
        "American Samoa",
        "Andorra",
        "Angola",
        "Anguilla",
        "Antarctica",
        "Antigua and Barbuda",
        "Argentina",
        "Armenia",
        "Aruba",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bermuda",
        "Bhutan",
        "Bolivia",
        "Bosnia and Herzegovina",
        "Bouvet Island",
        "Brazil",
        "British Indian Ocean Territory",
        "Brunei Darussalam",
        "Bulgaria",
        "Burkina Faso",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Cape Verde",
        "Cayman Islands",
        "Central African Republic",
        "Chad",
        "Chile",
        "China",
        "Christmas Island",
        "Cocos (Keeling) Islands",
        "Colombia",
        "Comoros",
        "Cook Islands",
        "Costa Rica",
        "Cote D'Ivoire",
        "Croatia",
        "Cuba",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Ethiopia",
        "Falkland Islands (Malvinas)",
        "Faroe Islands",
        "Fiji",
        "Finland",
        "France",
        "French Guiana",
        "French Polynesia",
        "French Southern Territories",
        "Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Gibraltar",
        "Greece",
        "Greenland",
        "Grenada",
        "Guadeloupe",
        "Guam",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Heard Island and Mcdonald Islands",
        "Holy See (Vatican City State)",
        "Honduras",
        "Hong Kong",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iran, Islamic Republic of",
        "Iraq",
        "Ireland",
        "Israel",
        "Italy",
        "Jamaica",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Kiribati",
        "North Korea",
        "South Korea",
        "Kuwait",
        "Kyrgyzstan",
        "Lao People's Democratic Republic",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libyan Arab Jamahiriya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macao",
        "Macedonia, the Former Yugoslav Republic of",
        "Madagascar",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Martinique",
        "Mauritania",
        "Mauritius",
        "Mayotte",
        "Mexico",
        "Micronesia, Federated States of",
        "Moldova, Republic of",
        "Monaco",
        "Mongolia",
        "Montserrat",
        "Morocco",
        "Myanmar",
        "Namibia",
        "Nauru",
        "Nepal",
        "Netherlands",
        "New Caledonia",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "Niue",
        "Norfolk Island",
        "Northern Mariana Islands",
        "Norway",
        "Oman",
        "Pakistan",
        "Palau",
        "Palestinian Territory, Occupied",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Pitcairn",
        "Poland",
        "Portugal",
        "Puerto Rico",
        "Qatar",
        "Reunion",
        "Romania",
        "Russian Federation",
        "Rwanda",
        "Saint Helena",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Pierre and Miquelon",
        "Saint Vincent and the Grenadines",
        "Samoa",
        "San Marino",
        "Sao Tome and Principe",
        "Saudi Arabia",
        "Senegal",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "Somalia",
        "South Africa",
        "South Georgia and the South Sandwich Islands",
        "Spain",
        "Sri Lanka",
        "Suriname",
        "Svalbard and Jan Mayen",
        "Swaziland",
        "Sweden",
        "Switzerland",
        "Syrian Arab Republic",
        "Taiwan",
        "Tajikistan",
        "Thailand",
        "Timor-Leste",
        "Togo",
        "Tokelau",
        "Tonga",
        "Trinidad and Tobago",
        "Tunisia",
        "Turkey",
        "Turkmenistan",
        "Turks and Caicos Islands",
        "Tuvalu",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom",
        "United States of America",
        "United States Minor Outlying Islands",
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Venezuela",
        "Viet Nam",
        "Virgin Islands, British",
        "Virgin Islands, U.S.",
        "Wallis and Futuna",
        "Western Sahara",
        "Yemen",
        "Åland Islands",
        "Bonaire, Sint Eustatius and Saba",
        "Curaçao",
        "Guernsey",
        "Isle of Man",
        "Jersey",
        "Montenegro",
        "Saint Barthélemy",
        "Saint Martin (French part)",
        "Serbia",
        "Sint Maarten (Dutch part)",
        "Kosovo",
    ],
    'order_status' =>[
        'Inquiry', 'Invoice Issued', 'Payment Received', 'Shipping', 'Document'
    ],  
];
// 