<?php

return [     
    'model_catgory' => [
        [
            'category_name' => 'Toyota',
            'children' => [
                'CAMRY', 'RAV4', 'RDX','LAND CRUISER', 'SAI', 'VOLTZ', 'GRAND HIACE', 'PRIUS', 'CALDINA', 'LITEACE VAN', 'ALLION', 'SUCCEED VAN','CORONA PREMIO', 'HIACE WAGON', 'RAUM', 'CELSIOR', 'DYNA TRUCK', 'NOAH', 'AVENSIS', 'TOYOACE', 'ISIS', 'COROLLA RUMION', 'VITZ', 'GAIA', 'PREVIA', 'BREVIS', 'LITEACE TRUCK', 'STARLET','COROLLA VERSO', 'HIACE VAN', 'RACTIS', 'CELICA', 'NADIA', 'AURIS', 'TOWNACE VAN', 'DYNA ROUTE VAN', 'IQ', 'RUSH', 'COROLLA FIELDER', 'VISTA ARDEO', 'FUN CARGO', 'PREMIO', 'BLADE', 'LITEACE NOAH', 'SPRINTER SEDAN', 'COROLLA VAN', 'YARIS', 'HIACE TRUCK', 'PROGRES', 'CARINA', 'MR-S', 'ARISTO', 'TOWNACE TRUCK', 'DUET', 'IPSUM', 'REGIUSACE VAN', 'COROLLA AXIO', 'VEROSSA', 'FORTUNER', 'PORTE', 'BELTA', 'LAND CRUISER PRADO', 'SPRINTER CARIB', 'COROLLA TOURING WAGON', 'HIACE COMMUTER', 'PROBOX WAGON', 'MARK X ZIO', 'AQUA', 'TOWNACE NOAH', 'CROWN MAJESTA', 'HILUX TRUCK', 'REGIUSACE COMMUTER', 'COROLLA', 'VELLFIRE', 'FJ CRUISER', 'PLATZ', 'BB', 'SPADE', 'COROLLA SPACIO', 'WILL VS', 'HARRIER', 'PROBOX VAN', 'CAMI', 'MARK X', 'ALTEZZA', 'TOURING HIACE', 'CROWN', 'HILUX SURF', 'REGIUS WAGON', 'COASTER', 'ESTIMA', 'PASSO SETTE', 'AVENSIS WAGON', 'VANGUARD', 'KLUGER', 'SOARER', 'COROLLA SEDAN', 'VOXY', 'GRANVIA', 'PRIUS ALPHA', 'CALDINA VAN', 'MARK II', 'ALPHARD', 'SUCCEED WAGON', 'CORSA', 'HILUX', 'CHASER', 'DYNA URBAN SUPPORTER', 'PASSO', 'AVENSIS VERSO', 'TUNDRA', 'IST', 'SIENTA', 'COROLLA RUNX'
            ]
        ],
        [
            'category_name' => 'MITSUBISHI',
            'children' => [
                'ROSA', 'FIGHTER MIGNON DUMP', 'DION', 'OUTLANDER', 'AERO MIDI', 'GREAT', 'RVR', 'COLT', 'LANCER CARGO', 'DELICA VAN', 'MINICAB VAN', 'GRANDIS', 'CHALLENGER', 'LANCER', 'DELICA TRUCK', 'MINICAB TRUCK', 'GALANT FORTIS', 'PAJERO MINI', 'CARISMA', 'L400', 'FIGHTER DUMP', 'DELICA SPACEGEAR', 'MINICA', 'FIGHTER MIGNON', 'PAJERO JR', 'CANTER GUTS', 'L300', 'SUPER GREAT', 'DELICA D5', 'LANCER EVOLUTION VIII', 'FIGHTER', 'PAJERO IO', 'CANTER', 'L200', 'STRADA', 'DELICA CARGO', 'LANCER EVOLUTION VII', 'EK WAGON', 'PAJERO', 'AIRTREK', 'JEEP', 'SPACE GEER', 'COLTPLUS', 'LANCER EVOLUTION'
            ]
        ],
        [
            'category_name' => 'Nissan',
            'children' => [
                'ALTIMA', 'ATLAS', 'SKYLINE GT-R', 'CLIPPER TRUCK', 'MURANO', 'DEXPERT', 'TERRANO REGULUS', 'DUALIS', 'PRESAGE', 'BLUEBIRD SYLPHY', 'VANETTE VAN', 'JUKE', 'SKYLINE COUPE', 'CIVILIAN', 'MOCO', 'TERRANO', 'DATSUN', 'PATROL GR', 'BIG THUMB', 'VANETTE TRUCK', 'HOMY VAN', 'SKYLINE', 'CIMA', 'MARCH', 'TEANA', 'CUBE CUBIC', 'PAO', 'URVAN', 'HOMY COACH', 'SERENA', 'CEDRIC', 'LIBERTY', 'SUNNY TRUCK', 'CUBE', 'OTTI', 'UD', 'FUGA', 'SAFARI', 'CARAVAN VAN', 'LATIO', 'SUNNY', 'CONDOR', 'NOTE', 'ALMERA', 'TIIDA LATIO', 'FAIRLADY Z', 'PRIMERA WAGON', 'CARAVAN COACH', 'X-TRAIL', 'LAFESTA', 'STAGEA', 'CLIPPER VAN', 'NAVARA', 'AD', 'TIIDA', 'ELGRAND', 'PRIMERA', 'CARAVAN', 'WINGROAD', 'KUON'
            ],
        ],
        [
            'category_name' => 'ISUZU',
            'children' => [
                'JOURNEY', 'ASKA', 'FORWARD', 'FARGO', 'WIZARD', 'ELF', 'MU', 'D-MAX', 'JUSTON', 'COMO', 'BIGHORN', 'GIGA'
            ],
        ],
        [
            'category_name' => 'Hino',
            'children' => [
                'RANGER', 'DOLPHIN', 'RANGER2', 'RAINBOW', 'PROFIA', 'LIESSE II', 'DUTRO', 'MELPHA'
            ],
        ],
        [
            'category_name' => 'Suzuki',
            'children' => [
                'WAGON R', 'ALTO', 'JIMNY SIERRA', 'SX4', 'JIMNY', 'SWIFT', 'GRAND ESCUDO', 'SPLASH', 'EVERY', 'LANDY', 'ESCUDO', 'KEI', 'CARRY', 'JIMNY WIDE'
            ],
        ],
        [
            'category_name' => 'Benz',
            'children' => [
                'C-Class', 'E-Class', 'Actros'
            ],
        ],
        [
            'category_name' => 'Volvo',
            'children' => [
                ''
            ],
        ],
        [
            'category_name' => 'BMW',
            'children' => [
                ''
            ],
        ],
        [
            'category_name' => 'Ford',
            'children' => [
                'RANGER'
            ],
        ],
        [
            'category_name' => 'Honda',
            'children' => [
                'Accord', 'Civic', 'Corvette', 'CR-V', 'ELYSION', 'INSIGHT', 'MDX', 'ELEMENT', 'HR-V', 'CAPA', 'LIFE', 'EDIX', 'STREAM', 'FREED', 'AVANCIER', 'LEGEND', 'CROSSROAD', 'STEP WGN', 'FIT SHUTTLE', 'AIRWAVE', 'INTEGRA', 'CR-Z', 'ODYSSEY', 'FIT HYBRID', 'ACTY VAN', 'INSPIRE', 'MOBILIO SPIKE', 'FIT', 'ACTY TRUCK', 'INSIGHT EXCLUSIVE', 'CIVIC HYBRID', 'MOBILIO'
            ],
        ],
        [
            'category_name' => 'Mazda',
            'children' => [
                'CX-5', 'ATENZA', 'LEVANTE', 'B-SERIES', 'TITAN', 'CAROL', 'FAMILIA VAN', 'AXELA SPORT', 'RX-8', 'BONGO VAN', 'FAMILIA S-WAGON', 'AXELA', 'ROADSTER', 'BONGO TRUCK', 'E2200', 'ATENZA WAGON', 'PREMACY', 'BONGO FRIENDEE', 'VERISA', 'DEMIO', 'ATENZA SPORT WAGON', 'MPV', 'BONGO BRAWNY VAN', 'TRIBUTE', 'CX-7', 'ATENZA SPORT', 'MAZDA5', 'BIANTE', 'TITAN DASH'
            ],
        ],
        [
            'category_name' => 'Daihatsu',
            'children' => [
                'TERIOS KID', 'BE-GO', 'HIJET', 'TERIOS', 'HIJET CARGO', 'NAKED', 'ESSE', 'MOVE', 'DELTA', 'MIRAGINO', 'COO', 'MIRA ES', 'BOON', 'MIRA'
            ],
        ],
        [
            'category_name' => 'Subaru',
            'children' => [
                'SAMBAR', 'EXIGA', 'IMPREZA SPORTSWAGON', 'PLEO', 'IMPREZA SPORTS', 'OUTBACK', 'IMPREZA G4', 'LEGACY TOURING WAGON', 'IMPREZA ANESIS', 'LEGACY B4', 'VIVIO', 'IMPREZA', 'IMPREZA WRX STI', 'SAMBAR TRUCK', 'FORESTER', 'IMPREZA WRX'
            ],
        ],
        [
            'category_name' => 'Volkswagen',
            'children' => [
                ''
            ],
        ],        
    ],
    'body_type' =>[
        'Bus', 'Truck', 'Van', 'SUV', 'Sedan', 'Pick Up', 'Machinery', 'Tractor'
    ],
    'fuel_type' =>[
        'Diesel', 'Electric', 'Gasoline', 'Hybrid', 'Petrol'
    ],
    'fuel_type' =>[
        'Diesel', 'Electric', 'Gasoline', 'Hybrid', 'Petrol'
    ],
    'drive_type' => [
        '2 Wheel', '4 Wheel'
    ],
    'transmission' =>[
        'Automatic', 'Manual', 'Semi-Automatic'
    ],  
    'steering' =>[
        'Right', 'Left'
    ],
    'doors' =>[
        1, 2, 3, 4, 5
    ],
    'country' =>[
        "Zambia",
        "Tanzania",
        "Uganda",
        "D.R Congo",
        "Zimbabwe",
        "Mozambique",
        "Malawi",
        "Sudan",
        "Kenya",
        "Botswana",
        "Burundi",
        "Afghanistan",
        "Albania",
        "Algeria",
        "American Samoa",
        "Andorra",
        "Angola",
        "Anguilla",
        "Antarctica",
        "Antigua and Barbuda",
        "Argentina",
        "Armenia",
        "Aruba",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bermuda",
        "Bhutan",
        "Bolivia",
        "Bosnia and Herzegovina",
        "Bouvet Island",
        "Brazil",
        "British Indian Ocean Territory",
        "Brunei Darussalam",
        "Bulgaria",
        "Burkina Faso",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Cape Verde",
        "Cayman Islands",
        "Central African Republic",
        "Chad",
        "Chile",
        "China",
        "Christmas Island",
        "Cocos (Keeling) Islands",
        "Colombia",
        "Comoros",
        "Cook Islands",
        "Costa Rica",
        "Cote D'Ivoire",
        "Croatia",
        "Cuba",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Ethiopia",
        "Falkland Islands (Malvinas)",
        "Faroe Islands",
        "Fiji",
        "Finland",
        "France",
        "French Guiana",
        "French Polynesia",
        "French Southern Territories",
        "Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Gibraltar",
        "Greece",
        "Greenland",
        "Grenada",
        "Guadeloupe",
        "Guam",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Heard Island and Mcdonald Islands",
        "Holy See (Vatican City State)",
        "Honduras",
        "Hong Kong",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iran, Islamic Republic of",
        "Iraq",
        "Ireland",
        "Israel",
        "Italy",
        "Jamaica",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Kiribati",
        "North Korea",
        "South Korea",
        "Kuwait",
        "Kyrgyzstan",
        "Lao People's Democratic Republic",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libyan Arab Jamahiriya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macao",
        "Macedonia, the Former Yugoslav Republic of",
        "Madagascar",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Martinique",
        "Mauritania",
        "Mauritius",
        "Mayotte",
        "Mexico",
        "Micronesia, Federated States of",
        "Moldova, Republic of",
        "Monaco",
        "Mongolia",
        "Montserrat",
        "Morocco",
        "Myanmar",
        "Namibia",
        "Nauru",
        "Nepal",
        "Netherlands",
        "New Caledonia",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "Niue",
        "Norfolk Island",
        "Northern Mariana Islands",
        "Norway",
        "Oman",
        "Pakistan",
        "Palau",
        "Palestinian Territory, Occupied",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Pitcairn",
        "Poland",
        "Portugal",
        "Puerto Rico",
        "Qatar",
        "Reunion",
        "Romania",
        "Russian Federation",
        "Rwanda",
        "Saint Helena",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Pierre and Miquelon",
        "Saint Vincent and the Grenadines",
        "Samoa",
        "San Marino",
        "Sao Tome and Principe",
        "Saudi Arabia",
        "Senegal",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "Somalia",
        "South Africa",
        "South Georgia and the South Sandwich Islands",
        "Spain",
        "Sri Lanka",
        "Suriname",
        "Svalbard and Jan Mayen",
        "Swaziland",
        "Sweden",
        "Switzerland",
        "Syrian Arab Republic",
        "Taiwan",
        "Tajikistan",
        "Thailand",
        "Timor-Leste",
        "Togo",
        "Tokelau",
        "Tonga",
        "Trinidad and Tobago",
        "Tunisia",
        "Turkey",
        "Turkmenistan",
        "Turks and Caicos Islands",
        "Tuvalu",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom",
        "United States of America",
        "United States Minor Outlying Islands",
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Venezuela",
        "Viet Nam",
        "Virgin Islands, British",
        "Virgin Islands, U.S.",
        "Wallis and Futuna",
        "Western Sahara",
        "Yemen",
        "Åland Islands",
        "Bonaire, Sint Eustatius and Saba",
        "Curaçao",
        "Guernsey",
        "Isle of Man",
        "Jersey",
        "Montenegro",
        "Saint Barthélemy",
        "Saint Martin (French part)",
        "Serbia",
        "Sint Maarten (Dutch part)",
        "Kosovo",
    ],
    'order_status' =>[
        'Pending', 'Reserved', 'Sales', 'Sold'
    ],  
];
